ARG DATABASE_URL
ARG SECRET_PASSWORD

FROM edgedb/edgedb

ENV EDGEDB_SERVER_PASSWORD=${SECRET_PASSWORD}

ENV EDGEDB_SERVER_TLS_CERT_MODE=generate_self_signed

ENV EDGEDB_SERVER_BACKEND_DSN_ENV=${DATABASE_URL}